package nour.movie_review_api.validation;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@AllArgsConstructor
public enum ExplicitWords {
    TWO_GIRLS_ONE_CUP("2g1c"),
    TWO_GIRLS_ONE_CUP_FULL("2 girls 1 cup"),
    ACROTOMOPHILIA("acrotomophilia"),
    ALABAMA_HOT_POCKET("alabama hot pocket"),
    ALASKAN_PIPELINE("alaskan pipeline"),
    ANAL("anal"),
    ANILINGUS("anilingus"),
    ANUS("anus"),
    APESHIT("apeshit"),
    ARSEHOLE("arsehole"),
    ASS("ass"),
    ASSHOLE("asshole"),
    ASSMUNCH("assmunch"),
    AUTO_EROTIC("auto erotic"),
    AUTOEROTIC("autoerotic"),
    BABY_BATTER("baby batter"),
    BABY_JUICE("baby juice"),
    BALL_GAG("ball gag"),
    BALL_GRAVY("ball gravy"),
    BALL_KICKING("ball kicking"),
    BALL_LICKING("ball licking"),
    BALL_SACK("ball sack"),
    BALL_SUCKING("ball sucking"),
    BAREBACK("bareback"),
    BARELY_LEGAL("barely legal"),
    BASTARD("bastard"),
    BBW("bbw"),
    BDSM("bdsm"),
    BEAVER_CLEAVER("beaver cleaver"),
    BEAVER_LIPS("beaver lips"),
    BESTIALITY("bestiality"),
    BIG_BREASTS("big breasts"),
    BIG_TITS("big tits"),
    BIMBOS("bimbos"),
    BITCH("bitch"),
    BITCHES("bitches"),
    BLACK_COCK("black cock"),
    BLOWJOB("blowjob"),
    BLOW_JOB("blow job"),
    BLOW_YOUR_LOAD("blow your load"),
    BLUMPKIN("blumpkin"),
    BONER("boner"),
    BOOB("boob"),
    BOOBS("boobs"),
    BOOTY_CALL("booty call"),
    BROWN_SHOWERS("brown showers"),
    BUKKAKE("bukkake"),
    BULLSHIT("bullshit"),
    BUNGHOLE("bunghole"),
    BUTT("butt"),
    BUTTCHEEKS("buttcheeks"),
    BUTTHOLE("butthole"),
    CAMEL_TOE("camel toe"),
    CAMGIRL("camgirl"),
    CAMWHORE("camwhore"),
    CLIT("clit"),
    CLITORIS("clitoris"),
    COCK("cock"),
    CUM("cum"),
    CUMMING("cumming"),
    CUMSHOT("cumshot"),
    CUNNILINGUS("cunnilingus"),
    CUNT("cunt"),
    DATE_RAPE("date rape"),
    DEEP_THROAT("deep throat"),
    DICK("dick"),
    DILDO("dildo"),
    DIRTY_SANCHEZ("dirty sanchez"),
    DOGGIE_STYLE("doggie style"),
    DOMINATRIX("dominatrix"),
    DOUBLE_PENETRATION("double penetration"),
    DP_ACTION("dp action"),
    DRY_HUMP("dry hump"),
    EAT_MY_ASS("eat my ass"),
    EJACULATION("ejaculation"),
    EROTIC("erotic"),
    ESCORT("escort"),
    FAG("fag"),
    FAGGOT("faggot"),
    FELCH("felch"),
    FELLATIO("fellatio"),
    FINGERBANG("fingerbang"),
    FISTING("fisting"),
    FUCK("fuck"),
    FUCKING("fucking"),
    GANGBANG("gangbang"),
    GAY_SEX("gay sex"),
    GENITALS("genitals"),
    GIANT_COCK("giant cock"),
    HANDJOB("handjob"),
    HARDCORE("hardcore"),
    HENTAI("hentai"),
    HOOKER("hooker"),
    HORNY("horny"),
    HOT_CHICK("hot chick"),
    INCEST("incest"),
    INTERCOURSE("intercourse"),
    JACK_OFF("jack off"),
    JAILBAIT("jailbait"),
    JERK_OFF("jerk off"),
    JIZZ("jizz"),
    KINKY("kinky"),
    LESBIAN("lesbian"),
    LOLITA("lolita"),
    LOVEMAKING("lovemaking"),
    MASTURBATE("masturbate"),
    MASTURBATION("masturbation"),
    MILF("milf"),
    MISSIONARY_POSITION("missionary position"),
    MOTHERFUCKER("motherfucker"),
    MUFF_DIVING("muff diving"),
    NIPPLE("nipple"),
    NIPPLES("nipples"),
    NSFW("nsfw"),
    NUDE("nude"),
    NUDITY("nudity"),
    ORGASM("orgasm"),
    ORGY("orgy"),
    PANTIES("panties"),
    PENIS("penis"),
    PISSING("pissing"),
    PLAYBOY("playboy"),
    PLEASURE_CHEST("pleasure chest"),
    PORN("porn"),
    PORNOGRAPHY("pornography"),
    PTHC("pthc"),
    PUSSY("pussy"),
    RECTUM("rectum"),
    RIMJOB("rimjob"),
    RIMMING("rimming"),
    SEMEN("semen"),
    SEX("sex"),
    SEXUAL("sexual"),
    SEXUALITY("sexuality"),
    SHAVED_PUSSY("shaved pussy"),
    SHIT("shit"),
    SHITTY("shitty"),
    SLUT("slut"),
    SPERM("sperm"),
    STRAP_ON("strap on"),
    SUCK("suck"),
    SUCKS("sucks"),
    SWINGER("swinger"),
    THREESOME("threesome"),
    THROATING("throating"),
    TIED_UP("tied up"),
    TITS("tits"),
    TOPLESS("topless"),
    TRANNY("tranny"),
    TWAT("twat"),
    UNDRESSING("undressing"),
    UPSKIRT("upskirt"),
    VAGINA("vagina"),
    VIAGRA("viagra"),
    VIBRATOR("vibrator"),
    VOYEUR("voyeur"),
    WANK("wank"),
    WET_DREAM("wet dream"),
    WHORE("whore"),
    XXX("xxx"),
    YIFFY("yiffy"),
    ZOOPHILIA("zoophilia");

    private final String word;

}
